### ISSUE TITLE
没什么问题

### ISSUE THREAD

**Issue by King-whb** [iphone5solo/PYSearch#1]
要是能支持 pod 就更好了

**Comment by iphone5solo** [comment]
@King-whb 嗯嗯。先推出来让大家测试使用。如果觉得好。没有多大问题就上传到CocoaPods

**Comment by iphone5solo** [comment]
@King-whb  现在已经支持pod的了，欢迎测试使用！谢谢您的反馈！

**Comment by King-whb** [comment]
恩恩  好的
