### ISSUE TITLE
搜索框错位

### ISSUE THREAD

**Issue by dongdong3344** [iphone5solo/PYSearch#103]
![2017-08-30 14 32 12](https://user-images.githubusercontent.com/22520640/29858478-26f1aa68-8d90-11e7-9f55-1cdb39d806e4.png)
设置了**Localization native development region**为china，取消按钮还是cancel,代码将其修改为
```
search?.navigationItem.rightBarButtonItem?.title = "取消"
```
然后就出现如上图所示错位情况。

另外A控制器 Present B(search)：

```
let nav = UINavigationController.init(rootViewController: search!)
        nav.modalPresentationStyle = .overCurrentContext
        nav.view.backgroundColor = UIColor.init(r: 80, g: 55, b: 50).withAlphaComponent(0.8)
        present(nav, animated: true, completion: nil)
```

如果A navigationBar 是透明的，我如何设置search的navBar不透明，换言之让2个控制器的navBar颜色一致。

还有个问题，假如有【本地文件】和【网络文件】2种类型可以搜索，当前的设计模式可以直接在search 这个view上添加2个segement进行切换吗？

**Comment by iphone5solo** [comment]
@dongdong3344 使用哪个设备和系统版本?

**Comment by iphone5solo** [comment]
demo 会出现这样的问题么？

**Comment by dongdong3344** [comment]
@iphone5solo 我使用的是Xcode 9 beta 2 版本，使用的模拟器iPhone 6, 10.3版本。我没有使用Demo验证，直接pod库文件至工程里的。

**Comment by iphone5solo** [comment]
@dongdong3344 可以先测试demo 有没有问题，如果没有问题的话，看看工程是不是有什么需要修改的。如果还没解决的话，欢迎联系我 QQ 499491531 备注：PYSearch #103

**Comment by dongdong3344** [comment]
更新至8.3可以修复错位问题。
