### ISSUE TITLE
存储的位置

### ISSUE THREAD

**Issue by Suzhibin** [iphone5solo/PYSearch#12]
注意到plist的保存路径 是NSDocumentDirectory 文件夹 ，能否自定义存储位置？

**Comment by iphone5solo** [comment]
谢谢您的反馈。现在我把搜索历史缓存路径宏定义放在PYSearchConst.h文件。如果想修改路径 可进入PYSearchConst.h 头文件修改 @Suzhibin

**Comment by Suzhibin** [comment]
@iphone5solo  每次应用启动后的 第一次点击 搜索都很卡  之后就不卡了。下次启动应用还是这样

**Comment by iphone5solo** [comment]
@Suzhibin  请描述一下你的运行环境 及 自定义的设置

**Comment by Suzhibin** [comment]
[self presentViewController:nav  animated:NO completion:nil];   设置 animated:YES 解决了
