### ISSUE TITLE
可以新增一个 search 的背景颜色属性, 是框架更完整

### ISSUE THREAD

**Issue by JCleqiang** [iphone5solo/PYSearch#14]

**Comment by iphone5solo** [comment]
您所说的背景颜色属性 具体指的是哪一个？ @JCleqiang

**Comment by JCleqiang** [comment]
uisearchbar 的背景颜色

**Comment by JCleqiang** [comment]
uisearchbar输入框的背景颜色

**Comment by iphone5solo** [comment]
你好！ 谢谢您的反馈，现在已经支持设置searbar的背景色。 请下载最新版，通过设置 searchBarBackgroundColor属性值设置背景色 @JCleqiang
