### ISSUE TITLE
PYHotSearchStyleRankTag类型，重新给值报错

### ISSUE THREAD

**Issue by app111** [iphone5solo/PYSearch#16]
PYSearchViewController.m 
Line:461 self.hotSearchTags.count 应改为 self.rankViews.count
![qq20161115-1](https://cloud.githubusercontent.com/assets/1449284/20292538/3e59a2d6-ab29-11e6-97ab-f93a0fb79d88.png)

**Comment by iphone5solo** [comment]
@app111 谢谢您反馈。 欢迎pull request !
