### ISSUE TITLE
热门搜索为空

### ISSUE THREAD

**Issue by SmallLion** [iphone5solo/PYSearch#2]
![image](https://cloud.githubusercontent.com/assets/7655798/19672598/93f80730-9aaa-11e6-93ba-5bdf64dceacf.png)

如图，如果热门搜索为空时，显示历史搜索记录会发生位置偏移

**Comment by SmallLion** [comment]
热门搜索为空时，设置历史搜索样式不是默认样式时，历史搜索记录不显示

**Comment by iphone5solo** [comment]
谢谢您的反馈。 热门搜索为空。真的出了问题。我找个时间修复下 @SmallLion

**Comment by iphone5solo** [comment]
现在两个BUG都修复了，请下载最新版测试。 再次感谢您的反馈！ @SmallLion
