### ISSUE TITLE
pod导入失败

### ISSUE THREAD

**Issue by Alamoalone** [iphone5solo/PYSearch#21]
[!] Unable to find a specification for `PYSearch`

**Comment by iphone5solo** [comment]
@Alamoalone  更新本地仓库再尝试

**Comment by Alamoalone** [comment]
@iphone5solo 去弄了一下，是我的cocopods太老了，更新了才安装成功，谢谢🙏

**Comment by iphone5solo** [comment]
@Alamoalone  客气，欢迎反馈！
