### ISSUE TITLE
热门搜索添加不到搜索历史中

### ISSUE THREAD

**Issue by iMaBiao** [iphone5solo/PYSearch#25]
热门搜索跳转页面与直接搜索跳转的页面不同，分别实现了代理方法（didSelectHotSearchAtIndex: 与 didSearchWithsearchBar: ）,但是在搜索历史中找不到热门搜索词，只能直接搜索时才会出现，请问怎么解决？

**Comment by iphone5solo** [comment]
@iMaBiao 谢谢您的反馈 现在已经修复！
