### ISSUE TITLE
想问下 热门搜索能否通过请求接口设置 谢谢

### ISSUE THREAD

**Issue by timelessLove** [iphone5solo/PYSearch#27]

**Comment by iphone5solo** [comment]
@timelessLove  可以的 请求获取的数组赋值hotSearches属性 即可自动刷新！

**Comment by timelessLove** [comment]
恩  那不是要到PYSearchViewController.m这个文件里在viewdidload方法里面 接口异步请求赋值给hotSearches属性   是这样去设置的吗 谢谢

**Comment by iphone5solo** [comment]
@timelessLove  直接对searchViewController对象的hotSearches属性赋值，即可自动刷新，注意：刷新界面最好是在主队列

**Comment by timelessLove** [comment]
恩 谢谢
