### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by luhuafei** [iphone5solo/PYSearch#3]
1, 搜索历史为空时, 2,搜索历史为默认时

**Comment by iphone5solo** [comment]
您好！这个BUG有人反馈了。现在已经修复。请下载最新版测试！谢谢您的反馈！ @luhuafei

**Comment by EggmanQi** [comment]
![pic](http://img.cuizhe.me/di/9VM0/Simulator_Screen_Shot_2016年10月26日_上午9.png)

搜索->进入新 vc->返回搜索

master 分支代码
