### ISSUE TITLE
默认样式问题

### ISSUE THREAD

**Issue by momodou4ever** [iphone5solo/PYSearch#30]
<img width="375" alt="2" src="https://cloud.githubusercontent.com/assets/6284023/21214940/da230312-c2d8-11e6-8272-190f702e23f2.png">
标题文字和清空按钮水平没有对齐 还有顶部的搜索框好像也有点问题 10.1的iPhone 7 模拟器

**Comment by iphone5solo** [comment]
@momodou4ever  这很明显是图片没有加载失败的问题。 你看一下为什么图片没有加载成功！

**Comment by shukaka** [comment]
searchbar如上图有黑色的边框，很不美观

**Comment by iphone5solo** [comment]
@shukaka 你也是 10.1的iPhone 7 模拟器出现的问题么？ 我觉得是图片没有加载成功的原因！

**Comment by shukaka** [comment]
@iphone5solo 是的，你是说clearimage没加载成功？你用demo跑一个7的模拟器试试看

**Comment by iphone5solo** [comment]
<img width="375" alt="31a77787-0d75-4cbc-a8a7-6b643b456e63" src="https://cloud.githubusercontent.com/assets/13819507/21284806/f0d7a330-c461-11e6-8303-35e7eef92cc8.png"> 10.2 iPhone7 模拟器正常

**Comment by iphone5solo** [comment]
我这边没下载10.1的 所以没测试！
