### ISSUE TITLE
热门搜索和历史搜索的顺序能不能换

### ISSUE THREAD

**Issue by HelloWT** [iphone5solo/PYSearch#31]
能提供一个接口,修改热门搜索和历史搜索的顺序.  而且有热门搜索的情况下,一般需求都是没搜索到内容,会在tableViewHeader显示一张图片,tableView显示热门搜索的内容!  可以考虑加上这个功能吗

**Comment by iphone5solo** [comment]
@HelloWT  暂时还没有提供！暂时只考虑大部分用户的需求，所以实在不好意思，您可以fork，自己在我的项目基础上实现！

**Comment by JackeyChen1015** [comment]
@iphone5solo 我也有这个需求，求提供

**Comment by iphone5solo** [comment]
@HelloWT  现在支持热门搜索和搜索历史顺序对换了，只要搜索历史的展示不是cell即可，可以直接设置`swapHotSeachWithSearchHistory`该属性为`YES`即可
```objc
/** 
 * 是否对换热门搜索和搜索历史，默认为：NO，即热门搜索在搜索历史上方，对换后搜索历史在热门搜索上方
 * 注意：该属性只适用于当搜索历史为标签类型才有效，即PYSearchHistoryStyle != PYSearchHistoryStyleCell
 */
@property (nonatomic, assign) BOOL swapHotSeachWithSearchHistory;
```

**Comment by CeaserW** [comment]
棒
