### ISSUE TITLE
Switch  landscape and Portrait issue in iPad

### ISSUE THREAD

**Issue by fanglichun** [iphone5solo/PYSearch#32]
when switching landscape and Portrait in iPad, UI layout frame become not exact.
<img width="1280" alt="2016-12-20 10 03 33" src="https://cloud.githubusercontent.com/assets/13825135/21335707/9b2d9ca0-c69b-11e6-8541-c4ee4eb55638.png">
![Uploading 屏幕快照 2016-12-20 上午10.03.29.png…]()

**Comment by fanglichun** [comment]
Can you deal with the iPad UI issue?

**Comment by iphone5solo** [comment]
@fanglichun 因为项目是已iPhone 为示例，所以iPad上布局错误是可以理解的！ 谢谢您的反馈！

**Comment by Huang-Libo** [comment]
如果需要适配 iPad(只含竖屏), 如何修改文字的大小, 是否可以暴露一些属性出来? 另外, 可以为 iPad 准备一套图标, 根据判断设备的类型来设置不同大小的图标.

**Comment by iphone5solo** [comment]
@fanglichun  Now, support vertical and horizontal screen on iPad and iPhone.
