### ISSUE TITLE
搜索结果超出显示范围

### ISSUE THREAD

**Issue by wufer** [iphone5solo/PYSearch#33]
当结果超出底部的时候显示不全 顶部有留白 tableView的frame设置错了？

**Comment by iphone5solo** [comment]
@wufer  麻烦附上图片！

**Comment by wufer** [comment]
<img width="320" alt="123" src="https://cloud.githubusercontent.com/assets/15667475/21342924/5b4670c4-c6cf-11e6-9a1c-bd4847b1db57.png">

**Comment by wufer** [comment]
最底部还有一条搜索结果

**Comment by wufer** [comment]
<img width="320" alt="345" src="https://cloud.githubusercontent.com/assets/15667475/21343011/b522a84c-c6cf-11e6-94fa-0c33d8703925.png">
感觉是导航栏的问题？

**Comment by iphone5solo** [comment]
@wufer  您下的是最新版么？

**Comment by wufer** [comment]
@iphone5solo 恩  ps:xcode的版本是8.1

**Comment by iphone5solo** [comment]
@wufer  好的 谢谢您的反馈。我尽快修复！

**Comment by wufer** [comment]
@iphone5solo 您好 试了一下 8886c4c 0.3.6 显示是正常的

**Comment by iphone5solo** [comment]
@wufer 现在已经修复，谢谢您的反馈，请下载最新版测试
