### ISSUE TITLE
pod 集成过来时有两个 PYSearch.h

### ISSUE THREAD

**Issue by Huang-Libo** [iphone5solo/PYSearch#34]
pod  集成过来的版本是
`pod 'PYSearch', '~> 0.4.5'`

**Comment by iphone5solo** [comment]
@Huang-Libo  为何？ 麻烦附上错误截图。

**Comment by Huang-Libo** [comment]
上次忘记截图了。目前我最近由于个人需求，改用拖入源码的方式在用 PYSearch，等我下次再通过 CocoaPods 集成时， 如果还遇到这个问题，就截图传上来。

**Comment by iphone5solo** [comment]
@Huang-Libo  好像是，我上次好像不小心把PYSearch.h也放在PYSearch.bundle里面了。然后及时删掉了，现在最新版本应该不会出问题了

**Comment by Huang-Libo** [comment]
好的!
