### ISSUE TITLE
Displayed texts are not localized

### ISSUE THREAD

**Issue by malinois** [iphone5solo/PYSearch#36]
Displayed texts are not localized : 

- PYSearchConst.m
- PYSearchViewController.m lines 141 and 236 

For example NSLocalizedString or accessibles properties.

Thanks !

**Comment by iphone5solo** [comment]
@malinois  Thank you for your feedback, I will try to make it support, if you want to participate, welcome to pull request!

**Comment by iphone5solo** [comment]
@malinois Now support localization, and welcomed the use of updated!
