### ISSUE TITLE
PYSearchViewController 页面的 contentSize 比实际高度少 64

### ISSUE THREAD

**Issue by Huang-Libo** [iphone5solo/PYSearch#37]
在集成 PYSearchViewController 后，当历史记录比较多需要滑动时，发现滑动不到底部，contentSize 的高度比实际少了一个导航栏的高度，应该是用户设置了 navigationBar.translucent 为 NO 后导致的，如果改为 YES 后这个问题就消失了。我有一个想法可以解决这类问题：通过在 PYSearchViewController 中检测用户是否有改变 translucent 的值，可以根据具体情况来设置 contentSize 的高度。

**Comment by iphone5solo** [comment]
已经修复，欢迎下载最新版测试！

**Comment by Huang-Libo** [comment]
还是少64
