### ISSUE TITLE
关于"预留接口"和"用户自定义"等建议

### ISSUE THREAD

**Issue by Huang-Libo** [iphone5solo/PYSearch#40]
少年有为的作者, 你好! 最近我在使用你写的这个框架, 感觉非常棒, 功能封装的很好, 很多时候只需要几行代码就能完成一个大功能. 另外, 我在使用的过程中也有一些心得和痛点, 算是抛砖引玉, 献丑了🙈

1. 关于命名,
  我们先聊聊 iOS SDK 中 UISearchController 的一个初始化方法, `- (instancetype)initWithSearchResultsController:(UIViewController *)searchResultsController;`这其中涉及两个 controller, searchController 和 searchResultsController, 一个是搜索的主页面, 另一个是搜索的结果页面. 

在 PYSearch 中, 对应功能的类分别为 PYSearchViewController 和 PYSearchSuggestionViewController, 此外, 在 PYSearchViewController 中还有一个属性 searchResultController, 三者的分别代表"搜索的主页面", "搜索的结果页面", "某条搜索结果的详情页", 

这个时候用过 UISearchController 的用户可能就会迷惑---searchResultController 到底是搜索的结果页面 还是 某个搜索结果的详情页? PYSearchSuggestionViewController 和 searchResultController 有什么关系? 我在用的时候就产生了此类疑惑, 看了源码之后才明白 PYSearchSuggestionViewController 和 UISearchController 中的 searchResultsController 是一个意思. 我个人认为一个好的设计, 是不需要用户关心接口的实现的, 能见名知意.

  我建议这种情况下类或属性的命名和原生 API 保持类似的风格, PYSearchSuggestionViewController 可以改为 PYSearchResultsViewController 或 PYSearchResultsController; 而"某一条搜索结果的详情页" iOS 的 SDK 没有涉及, 这一步留给了用户自己在 searchResultsController 中处理. PYSearch 中对应的这个属性 searchResultController 可以改名为 resultDetailController.

2. 关于"自定义"的痛点
这条内容又和 PYSearchResultsViewController 有关, 还得聊到 iOS SDK 中的 `- (instancetype)initWithSearchResultsController:(UIViewController *)searchResultsController;`. 在这个方法中, 搜索页面关联的 searchResultsController 是 UIViewController 类型的, 所以搜索结果页可以是单个 UITableView 页面, 也可以是复杂一点的一个 ScrollView 中嵌套的多个 tableView (比如"支付宝"的搜索页面), 总而言之, 这是一个用户可自定义的页面, 而不是局限为一个 tableView. 所以我建议搜索结果页的功能可以这样改: 搜索结果页的类型默认是UIViewController, 如果用户没有特别指定, 则只包含单个 tableView; 如果用户实现了自己的 searchResultsController, 则使用用户自定义的 controller 作结果页.

3. 是一个预留控件的问题, 比如在 searchBar 的左边, 有时需要做一个可点击的下拉分类选择控件(参考淘宝的搜索页), searchBar 的右边, 有时需要显示一个语音输入按钮,根据用户的设置来决定是否显示, 不知道 PYSearch 目前也没有实现这个功能?

**Comment by iphone5solo** [comment]
@Huang-Libo 首先谢谢您的建议！其次，可能我的命名还不够明确导致您的误解，这里的PYSearchSuggestionViewController是用来显示搜索建议的，根据你输入内容，动态从服务器获取搜索建议，并非您理解的搜索结果，searchResultController<UIViewController>才是真是用来显示搜索结果的，而非是结果详情，关于预留空间的问题，因为是自定义，所以我能提供的就是相关控件，如可通过searchViewControlelr的navagationBar和searchBar的相关设置来达到需求！

**Comment by Huang-Libo** [comment]
也许我们俩所说的搜索结果不是同一个东西，我指的是搜索结果列表，你指的是列表中某一条的详情。iOS SDK 中`- (instancetype)initWithSearchResultsController:(UIViewController *)searchResultsController;`的`searchResultsController`是 搜索的 results，这个应该没问题吧？

**Comment by iphone5solo** [comment]
我用我使用美团的两张截图来说明一下我想表达的意思吧！估计和你想的是一样的
1. 搜索建议界面
<img width="356" alt="default" src="https://cloud.githubusercontent.com/assets/13819507/21667360/68fe8f60-d333-11e6-87d6-30687305f953.png">

2. 搜索结果列表
<img width="355" alt="default" src="https://cloud.githubusercontent.com/assets/13819507/21667363/710d6eec-d333-11e6-9fe5-f56838e1fa4c.png">

**Comment by Huang-Libo** [comment]
不好意思, 是我理解错了, PYSearch 和 UISearchController 中的 searchResultController 都是我所理解的"搜索结果列表页面", 而 PYSearchSuggestionViewController 类似于搜索引擎在写入关键字时给的关键字提示页面, 点击某个关键字后才显示的是搜索结果列表页面. 

另外我有一个问题, 如果我把 searchSuggestionHidden 设置为 YES, searchResultShowMode 设置为 PYSearchResultShowModeEmbed, 如何在 searchBar 中输入文字时动态刷新 searchResultController?

**Comment by Huang-Libo** [comment]
看了你的图, 我秒懂了(美团的搜索功能很典型, 👍), 之前聊的内容应该是搜索两种搜索逻辑:

第一种: APP Store 或 美团 等, 在输入搜索内容时显示搜索建议, 点击某个搜索建议再进入搜索结果列表页;

第二种: 支付宝等, 在输入搜索内容时直接显示搜索结果列表页.

这应该是两种比较常见的搜索模式, 第二种应该是第一种的简化版, PYSearch 属于功能比较齐的第一种😁

**Comment by iphone5solo** [comment]
关于 searchBar 中输入文字时动态刷新 searchResultController的问题是 你只要成为searchViewController的一下代理方法
```objc
 /** 搜索框文本变化时，显示的搜索建议通过searchViewController的searchSuggestions赋值即可 */
 - (void)searchViewController:(PYSearchViewController *)searchViewController  searchTextDidChange:(UISearchBar *)seachBar searchText:(NSString *)searchText;
```
可以根据searchText来动态获取搜索结果更新searchResultController的界面！

**Comment by iphone5solo** [comment]
关于 searchBar 中输入文字时动态刷新 searchResultController的问题是 你只要成为searchViewController的一下代理方法
```objc
 /** 搜索框文本变化时，显示的搜索建议通过searchViewController的searchSuggestions赋值即可 */
 - (void)searchViewController:(PYSearchViewController *)searchViewController  searchTextDidChange:(UISearchBar *)seachBar searchText:(NSString *)searchText;
```
可以根据searchText来动态获取搜索结果更新searchResultController的界面！

**Comment by Huang-Libo** [comment]
这个代理好像只能动态更新PYSearchSuggestionViewController

**Comment by iphone5solo** [comment]
可能是你没理解我这边的searchResultController，这个searchResultController是用户提供的，所以是否动态更新取决于用户，我这边只能提供动态的搜索文本searchText，还有将用户的searchResultController搜索结果控制器的view呈现出来，所以是否动态修改，取决于用户怎么修改自己的searchResultController的视图，我这边只负责呈现搜索结果界面，至于怎么呈现，取决于用户，具体可以参考如下注释：
```objc
/** 
 * 搜索结果控制器
 * 当searchResultShowMode == PYSearchResultShowModePush时，
 * 将目的控制器给该属性赋值，即Push到searchResultController控制器
 * 当searchResultShowMode == PYSearchResultShowModeEmbed时，
 * 将目的控制器给该属性赋值，即将searchResultController.view添加到self.view
 */
@property (nonatomic, strong) UIViewController *searchResultController;
```

**Comment by Huang-Libo** [comment]
是的, 在` - (void)searchViewController:(PYSearchViewController *)searchViewController  searchTextDidChange:(UISearchBar *)seachBar searchText:(NSString *)searchText;`代理中可以实时拿到输入的内容, 这个没问题, searchResultShowMode 我也设置成了 PYSearchResultShowModeEmbed. 但是有一个效果一直没找到怎么实现, 比如在 searchBar 中输入内容时, searchResultController 不会立即显示出来, 只有在点击了键盘上的"搜索"按钮时, 才会显示 searchResultController. 如何在输入文字的时候就显示 searchResultController?

**Comment by Huang-Libo** [comment]
发现一个小问题,

 /** 搜索框文本变化时，显示的搜索建议通过searchViewController的searchSuggestions赋值即可 */
` - (void)searchViewController:(PYSearchViewController *)searchViewController  searchTextDidChange:(UISearchBar *)seachBar searchText:(NSString *)searchText;`

seachBar 应该改为 searchBar

**Comment by Huang-Libo** [comment]
还有一个建议:

在`- (BOOL)searchBarShouldBeginEditing:(UISearchBar *)searchBar`代理方法中有这样一行语句:
```
// 搜索结果隐藏
self.searchResultController.view.hidden = YES;
```
也就是说只有点击了搜索栏, searchResultController 的 view 就隐藏了, 这个行为和 APP Store 是一样的, 本身没有问题. 但是有时候产品需要想输入的时候就停留在 searchResultController 中, 所以我认为 searchResultController 的 view 此时是否隐藏可以增加一个属性让用户自己设置.

**Comment by iphone5solo** [comment]
嗯嗯 谢谢您的建议 现在已经根据您的建议做了代码优化 提供了以下两个属性用于内嵌搜索结果的显示控制
```objc
/** 
 * 是否显示搜索结果当搜索文本改变时（默认为NO）
 * 该属性只要当searchResultShowMode == PYSearchResultShowModeEmbed时，才会生效
 */
@property (nonatomic, assign) BOOL showSearchResultWhenSearchTextChanged;
/**
 * 是否显示搜索结果当搜索框重新聚焦(再次成为第一响应者时)（默认为NO）
 * 该属性只要当searchResultShowMode == PYSearchResultShowModeEmbed时，才会生效
 */
@property (nonatomic, assign) BOOL showSearchResultWhenSearchBarRefocused;
```

**Comment by iphone5solo** [comment]
@Huang-Libo  鉴于你这么活跃 邀请你进去PYSearch开源项目组：595939654 备注：GitHub #40

**Comment by Huang-Libo** [comment]
谢邀, 已经申请了.

我 pull 了更新, 发现忽略文件有点问题, 接着我去查看`.gitignore`, 发现其文件名有问题, 打开终端发现文件名前面多了一个空格.

<img width="520" alt="2017-01-06 10 25 29" src="https://cloud.githubusercontent.com/assets/12227130/21705440/e80c8736-d3fa-11e6-8896-5006d955f44d.png">

<img width="655" alt="2017-01-06 10 26 21" src="https://cloud.githubusercontent.com/assets/12227130/21705442/e85a8d0a-d3fa-11e6-8f50-886a44d83f2f.png">
