### ISSUE TITLE
建议改造成UIsearchController会比UISearchBar+UIButton更灵活

### ISSUE THREAD

**Issue by Steven-Yung** [iphone5solo/PYSearch#41]
如题

**Comment by Huang-Libo** [comment]
@Steven-Yung 
UIsearchController 是 iOS8 才有的, 目前 PYSearch 支持到了 iOS7

**Comment by Steven-Yung** [comment]
@Huang-Libo iOS7有UISearchDisplayController,现在有个问题，当我从上一个页面用Push方式直接跳转到搜索页面的时候，搜索框和取消按钮重合了，你可以改你的demo运行看看，我改成了下面这样
![112211](https://cloud.githubusercontent.com/assets/8358206/21749812/ccdf703e-d5e1-11e6-9d7a-aae506aee97e.png)
效果：
![225](https://cloud.githubusercontent.com/assets/8358206/21749811/baa07882-d5e1-11e6-82b6-a187e0f152d9.png)

**Comment by Huang-Libo** [comment]
因为导航控制器给你在最右边自动加了一个返回按钮, 所以布局乱了, 目前应该是没有考虑这种情况

**Comment by iphone5solo** [comment]
@Steven-Yung 谢谢您的反馈，先已经修复，欢迎下载最新版，或执行pod update! 测试
