### ISSUE TITLE
搜索历史记录无法覆盖

### ISSUE THREAD

**Issue by taojeff** [iphone5solo/PYSearch#43]
博主，我在使用你的demo的时候我只想使用你那个热门彩色有序排序功能的样式。可是我在拉取代码的时候其它的都拉取的差不多了，可是就差一个搜索历史的header地方不理想，对于header的地方总是有两处显示，下面三处截图就是我的拉取的代码和
![img_0029](https://cloud.githubusercontent.com/assets/19642626/21791798/64ccaf26-d720-11e6-9f26-51a5a77caa0c.PNG)
![24c035dd-a99b-412b-abdc-1c93a0dbf73a](https://cloud.githubusercontent.com/assets/19642626/21791827/9bffb2e0-d720-11e6-90e4-3c330b7e4d5d.png)
![a7d4a958-0bcb-473a-ab14-89375cabe0f9](https://cloud.githubusercontent.com/assets/19642626/21791828/9cdb2780-d720-11e6-9e04-222d721544a9.png)

**Comment by iphone5solo** [comment]
@taojeff 你可能部分代码没有拉取，你加我QQ：499491531 备注：GitHub #43
