### ISSUE TITLE
搜索结果向下偏移

### ISSUE THREAD

**Issue by wufer** [iphone5solo/PYSearch#45]
<img width="375" alt="51e7deeb-9f2b-458b-8d43-6bbcf9dabc57" src="https://cloud.githubusercontent.com/assets/15667475/22049948/d24cf0cc-dd71-11e6-8f70-6faea2d65106.png">

**Comment by wufer** [comment]
<img width="770" alt="55c0f36c-4437-4882-8d14-fffbf2c5270c" src="https://cloud.githubusercontent.com/assets/15667475/22052621/33b9527e-dd86-11e6-90a4-bd6ac9010f08.png">

**Comment by iphone5solo** [comment]
@wufer 这是根据界面微调而得！内部已经处理，所以您就不需要处理了 ！只需要实现数据源方法更新界面即可！

**Comment by wufer** [comment]
@iphone5solo  可是这里不改成30 就是会出现第一张图的情况 整个搜索建议的tableview向下偏移30 您看看这是我这里的个别情况吗？demo是最新的

**Comment by wufer** [comment]
仔细看了看 大概懂您什么意思了 貌似是我对键盘的处理有问题

**Comment by iphone5solo** [comment]
@wufer  是的，内部对30进行了处理。 如果没有必要 最好不要调整
