### ISSUE TITLE
如果NavigationBar是不透明的，当搜索历史超过屏幕后，“清空历史搜索”会拉不上来

### ISSUE THREAD

**Issue by dengshunlai** [iphone5solo/PYSearch#49]
如果NavigationBar是不透明的，当搜索历史超过屏幕后，“清空历史搜索”会拉不上来

**Comment by iphone5solo** [comment]
@dengshunlai  可否再描述一下。 或者配上Gif图片会更好说明问题，如果您已经有解决方案，欢迎PR！

**Comment by dengshunlai** [comment]
在你的demo，PYSearchExampleController.m 文件第74行插入一句 nav.navigationBar.translucent = NO;  就会出现这个问题。
如下：
// 5. 跳转到搜索控制器
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:searchViewController];
    nav.navigationBar.translucent = NO;
    [self presentViewController:nav animated:YES completion:nil];

**Comment by iphone5solo** [comment]
@dengshunlai  谢谢您的反馈，现在已经修复，欢迎下载最新版测试 或者 执行pod update 更新测试！ 元宵节快乐！
