### ISSUE TITLE
点击热门搜索任意一个跳转到下一个界面后，点击返回，上个界面整体下移了几十像素

### ISSUE THREAD

**Issue by ChandlerBinGuo** [iphone5solo/PYSearch#52]
你好，当我在7plus模拟器上点击热门搜索任意一个跳转到下一个界面后，点击返回，上个界面整体下移了几十像素。不知道其他机型或真机是否有这个问题。

**Comment by iphone5solo** [comment]
@ChandlerBinGuo  谢谢您的反馈，现在已经及时修复，欢迎下载最新版测试！
