### ISSUE TITLE
iOS7未适配

### ISSUE THREAD

**Issue by hirat** [iphone5solo/PYSearch#54]
[UIImage imageNamed: inBundle: compatibleWithTraitCollection:]
方法iOS8+ only

**Comment by iphone5solo** [comment]
@hirat  实在不好意思，现在我电脑上只有Xcode 8和Xcode 7.3 没有iOS 7.x的模拟器，所以展示没办法适配iOS 7 希望如果你解决了 欢迎PR！或者叫我如何在macOS Sierra系统中使用Xcode 6.4 或者在Xcode 8 或者Xcode 7.3中安装iOS 7.x模拟器。我弄了一下午还是失败了！

**Comment by hirat** [comment]
我也不知道怎么安装iOS7模拟器，刚刚提交了一个PullRequest，麻烦看一下。

**Comment by iphone5solo** [comment]
@hirat 虽然我没有iOS 7模拟器测试，但是我看了代码 基本没有多少问题。 希望您能继续维护iOS 7的适配，小提示：编码风格尽量和源码一致！谢谢您的提交！让该项目更加强大！
