### ISSUE TITLE
键盘存在与否，影响数据的整体显示

### ISSUE THREAD

**Issue by honeycao** [iphone5solo/PYSearch#61]
问题：实现了delegate 并写了 didSelectHotSearchAtIndex 和 didSelectSearchHistoryAtIndex 方法，当点击搜索历史记录时，此时键盘是收起来的，那么弹出来的搜索建议不能显示完全，底部总有几个滚不上来，当我将键盘一直显示的时候，那么是可以完全显示的，但是不想键盘一直显示，然后这个问题不知道怎么解决。。。

**Comment by iphone5solo** [comment]
@honeycao 谢谢您的反馈！最近比较忙。我尽快找个时间修复 或者您发现了问题所在，欢迎修复，然后PR!

**Comment by iphone5solo** [comment]
@honeycao  加我QQ：499491531@qq.com 备注：GitHub#61

**Comment by keepJion** [comment]
不知道有什么好的解决方案没有?

**Comment by Arthurcsh** [comment]
热门、历史记录的布局都是固定的，没法动态配置吗？

**Comment by iphone5solo** [comment]
@Arthurcsh 如果需要动态配置，建议`fork`，然后修改里面的布局代码即可！

**Comment by iphone5solo** [comment]
@honeycao  @keepJion  现在已经修复，欢迎更新使用，谢谢反馈，前一段时间比较忙，未能及时修复，深感抱歉！
