### ISSUE TITLE
使用代理执行搜索，搜索历史不会被保存，请作者查看一下，需要在1112行的方法里，return之前需要调用[self saveSearchCacheAndRefreshView]

### ISSUE THREAD

**Issue by AntHuiZi** [iphone5solo/PYSearch#62]
不使用block，使用代理，执行搜索时，搜索历史不会被保存，请作者查看。经过查看，发现需要在1112行的方法里，return之前需要调用[self saveSearchCacheAndRefreshView]；
例：
#pragma mark - UISearchBarDelegate
- (void)searchBarSearchButtonClicked:(UISearchBar *)searchBar
{
    // 如果代理实现了代理方法则调用代理方法
    if ([self.delegate respondsToSelector:@selector(searchViewController:didSearchWithsearchBar:searchText:)]) {
        [self.delegate searchViewController:self didSearchWithsearchBar:searchBar searchText:searchBar.text];
        #  [self saveSearchCacheAndRefreshView];
        return;
    }
    // 如果有block则调用
    if (self.didSearchBlock) self.didSearchBlock(self, searchBar, searchBar.text);
    
    // 缓存数据并且刷新界面
    [self saveSearchCacheAndRefreshView];
}
麻烦作者查看，是否是这里的问题！谢谢！

**Comment by iphone5solo** [comment]
@AntHuiZi  是的。这里出了点问题，现在修复了。谢谢反馈！
