### ISSUE TITLE
建议在保存搜索历史的方法里加入一个判断“不保存空格”

### ISSUE THREAD

**Issue by AntHuiZi** [iphone5solo/PYSearch#64]
`/** 进入搜索状态调用此方法 */
- (void)saveSearchCacheAndRefreshView
{
    UISearchBar *searchBar = self.searchBar;
    // 回收键盘
    [searchBar resignFirstResponder];
   /***********去除搜索词的空格******去除全部空格*********/
    NSString *strUrl = [searchBar.text stringByReplacingOccurrencesOfString:@" " withString:@""];
    /***********判断搜索的词长度不为0***************/
    if (self.showSearchHistory && strUrl.length > 0) { // 只要显示搜索历史才会缓存
        
        // 先移除再刷新
        [self.searchHistories removeObject:strUrl];
        [self.searchHistories insertObject:strUrl atIndex:0];
        
        // 移除多余的缓存
        if (self.searchHistories.count > self.searchHistoriesCount) {
            // 移除最后一条缓存
            [self.searchHistories removeLastObject];
        }
        // 保存搜索信息
        [NSKeyedArchiver archiveRootObject:self.searchHistories toFile:self.searchHistoriesCachePath];
        
        // 刷新数据
        if (self.searchHistoryStyle == PYSearchHistoryStyleCell) { // 普通风格Cell
            [self.baseSearchTableView reloadData];
        } else { // 搜索历史为标签
            // 更新
            self.searchHistoryStyle = self.searchHistoryStyle;
        }
    }
    
    // 处理搜索结果
    [self handleSearchResultShow];
}
`

**Comment by iphone5solo** [comment]
@AntHuiZi  谢谢你的反馈。现在已经新增属性去控制是否删除搜索文本的空格，默认为YES！
```OBJC
/** 是否去除搜索词中的空格，默认为YES */
@property (nonatomic, assign) BOOL removeSpaceOnSearchString;
```
