### ISSUE TITLE
缓存路径问题

### ISSUE THREAD

**Issue by iOSWynter** [iphone5solo/PYSearch#68]
PYSearchViewController.m 中 closeDidClick:方法中保存搜索缓存路径没使用searchHistoriesCachePath属性，而是使用了PYSEARCH_SEARCH_HISTORY_CACHE_PATH宏定义，导致自定义路径保下的搜索缓存删除失败

**Comment by iphone5solo** [comment]
@iOSWynter  谢谢提醒! 现在已经修复！
