### ISSUE TITLE
热门搜索不能点击问题

### ISSUE THREAD

**Issue by Wanglw2015** [iphone5solo/PYSearch#69]
历史搜索style使用PYSearchHistoryStyleNormalTag,热门搜索style使用PYHotSearchStyleColorfulTag,
交换位置后,清空历史搜索后,热门搜索不能点击,看层级结构,好像是searchHistoryView拦截了点击事件

**Comment by iphone5solo** [comment]
@Wanglw2015  谢谢反馈，现在已经修复！
