### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by luchaoqun123** [iphone5solo/PYSearch#7]
首先:很好的demo
我的工程里设置了navigationVC的两个属性;
问题1:搜索框里看不到光标;
问题儿:搜索建议页面会向下偏移
下面是我设置的navigationVC的属性,当我代码里注释这两行就不会有上面的两个问题.
`[[UINavigationBar appearance] setTintColor:[UIColor whiteColor]];
    [[UINavigationBar appearance] setBackgroundImage:[UIImage imageName:@"someColorfulImage"] forBarMetrics:UIBarMetricsDefault];`

and PYSearchViewController.m  line 120  ,why set tableview.contentInset top 30?

**Comment by iphone5solo** [comment]
@luchaoqun123 
首先：非常感谢您的反馈
关于问题一：因为您设置的navigationBar的主题为白色，和该项目的背景色是一样的，所以光标是存在的。只是两个都是白色。你看不到。
关于问题二：搜索页面向下偏移，这个BUG我昨天发现了，也已经修复了，请下最新版测试！

and set tableView.contentInset to 30 just mark it show more tasteful！
