### ISSUE TITLE
点击取消按钮的问题

### ISSUE THREAD

**Issue by MysteryRan** [iphone5solo/PYSearch#71]
点击取消按钮的时候 自定义转场无法实现

**Comment by iphone5solo** [comment]
@MysteryRan  请详细描述一下问题！

**Comment by MysteryRan** [comment]
在取消按钮中 实现自己的pop方法 无法调用 UINavigationControllerDelegate代理方法

**Comment by iphone5solo** [comment]
@MysteryRan 加下我QQ499491531 备注：#71
