### ISSUE TITLE
重写PYSearchViewControllerDataSource时 第一次输入不显示建议搜索

### ISSUE THREAD

**Issue by lifeMiik** [iphone5solo/PYSearch#77]
当重写建议搜索页面时第一次搜索是不会有结果的，但是第二次输入时是有结果的。Thanks！。

**Comment by iphone5solo** [comment]
@lifeMiik 谢谢您的反馈！现在已经修复！Enjoy it! ☕️

**Comment by lifeMiik** [comment]
还是有一个bug的，当热门搜索为空时，第一次搜索，搜索建议没有结果。实际上有结果的。
