### ISSUE TITLE
真机下布局问题

### ISSUE THREAD

**Issue by Li-Yudong** [iphone5solo/PYSearch#8]
![img_2197](https://cloud.githubusercontent.com/assets/18612795/19826389/83183c46-9dbb-11e6-857b-58b89a10e74e.PNG)
![img_2198](https://cloud.githubusercontent.com/assets/18612795/19826390/83192be2-9dbb-11e6-833d-66a37379c4fe.PNG)
真机下布局问题依旧存在

**Comment by iphone5solo** [comment]
@Li-Yudong 您是下载最新版测试的么。我这边真机测试没问题。 如果您是最新版测试，还是出BUG，可以提供一下测试环境！ 谢谢！

**Comment by Li-Yudong** [comment]
我刚下载的,在我  Xcode8.0 运行iOS10   5S真机上面仍然有问题

**Comment by iphone5solo** [comment]
我这边也是Xcode8.0 5S真机， iOS10 运行没出现你说的问题。倒发现了另外一个问题：点击右边的“X”没有正常相应！

**Comment by Li-Yudong** [comment]
你把你最新的测试发我一份 li_yudong@126.com 谢谢 我再试试

**Comment by iphone5solo** [comment]
已发送

**Comment by Li-Yudong** [comment]
已收到 
我图片勾选的这几种样式没有问题 ,其他几种样式依然存在问题
![img_2199](https://cloud.githubusercontent.com/assets/18612795/19826828/1e2017fc-9dc8-11e6-9cb5-4ab8c057a50f.PNG)

**Comment by iphone5solo** [comment]
你加我QQ499491531联系，备注：GitHub

**Comment by Li-Yudong** [comment]
完美兼容了  感谢! 😊
