### ISSUE TITLE
iOS11上有Bug

### ISSUE THREAD

**Issue by github410117** [iphone5solo/PYSearch#87]
![image](https://user-images.githubusercontent.com/15375736/27210367-8b25e32e-5284-11e7-89d5-f74ddc490ec0.png)
在iOS11的模拟器上不会显示搜索框！希望能解决一下，万分感激！

**Comment by iphone5solo** [comment]
@github410117 谢谢您的反馈，目前还没更新XCode 9 Beta版 现在在下载 请您耐心等待，我下载完将第一时间适配iOS 11

**Comment by github410117** [comment]
麻烦您了！谢谢！

**Comment by iphone5solo** [comment]
@github410117  实在不好意思，今天晚上送大四学长，现在才修复！欢迎下载最新版测试使用！
