### ISSUE TITLE
请问搜索框背景色怎么控制的

### ISSUE THREAD

**Issue by LvJianfeng** [iphone5solo/PYSearch#9]

**Comment by LvJianfeng** [comment]
你用的透明图片设置search的背景，真机6p没有生效。
我现在处理的方法是imagewithcolor来处理的
- (UIImage *)imageWithColor:(UIColor *)color size:(CGSize)size
                 {
                 CGRect rect = CGRectMake(0, 0, size.width, size.height);
                 UIGraphicsBeginImageContext(rect.size);
                 CGContextRef context = UIGraphicsGetCurrentContext();
                 
                 CGContextSetFillColorWithColor(context, [color CGColor]);
                 CGContextFillRect(context, rect);
                 
                 UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
                 UIGraphicsEndImageContext();
                 
                 return image;
             }

searchBar.backgroundImage = [self imageWithColor:[UIColor clearColor] size:_searchBar.bounds.size];

**Comment by LvJianfeng** [comment]
你用的透明图片设置search的背景，真机6p没有生效。
我现在处理的方法是imagewithcolor来处理的

    - (UIImage *)imageWithColor:(UIColor *)color size:(CGSize)size
    {
        CGRect rect = CGRectMake(0, 0, size.width, size.height);
        UIGraphicsBeginImageContext(rect.size);
        CGContextRef context = UIGraphicsGetCurrentContext();
        CGContextSetFillColorWithColor(context, [color CGColor]);
        CGContextFillRect(context, rect);
        UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        return image;
     }

     searchBar.backgroundImage = [self imageWithColor:[UIColor clearColor] size:_searchBar.bounds.size];

**Comment by iphone5solo** [comment]
你可以 pull request 做好注释，注意代码风格！ @LvJianfeng 鼓励参与项目！
