### ISSUE TITLE
历史记录数组中能否存储自定义对象?

### ISSUE THREAD

**Issue by LSRain** [iphone5solo/PYSearch#92]
当前只是存储了Label,但是我需要更多的对象属性

**Comment by iphone5solo** [comment]
@LSRain 这个目前没有做拓展！

**Comment by LSRain** [comment]
恩，我现在修改了一下，点击搜索记录后

**Comment by LSRain** [comment]
恩，我现在修改了一下，1. 实现`PYSearchViewController Delegate`自定义搜索cell  2. 点击搜索记录cell后归档缓存记录对象 3. 解档新对象数组显示历史记录. 至此历史记录数组中便存储了我自定义的模型，解决了我的需求   ~~感谢~~

**Comment by LSRain** [comment]
恩，我现在修改了一下，1. 实现`PYSearchViewController Delegate`自定义搜索`cell` 2. 点击搜索记录`cell`后`归档`缓存记录对象 3. `解档`新对象数组显示历史记录. 至此历史记录数组中便存储了我自定义的模型，解决了我的需求 感谢!

**Comment by iphone5solo** [comment]
@LSRain  Nice!
