### ISSUE TITLE
在Xcode 9  iOS11  汉语版运行有bug

### ISSUE THREAD

**Issue by Gang679** [iphone5solo/PYSearch#99]
#在Xcode 9  iOS11  汉语版运行有bug 具体的问题看下面的 截图

![1](https://user-images.githubusercontent.com/15606809/29405426-7373cca6-8370-11e7-9145-60a1e6428257.png)

**Comment by Gang679** [comment]
已经修改，稍后PR上去，你看看

**Comment by dongdong3344** [comment]
没有修复这个问题。plist文件Localization native development region 设置china，但是取消按钮还是显示英文。searchVC?.navigationItem.rightBarButtonItem?.title = "取消"  如果使用此代码直接修改，则会出现上图这样的情况。
